# Generated by Django 4.1.5 on 2023-05-02 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='tracking_no',
            field=models.CharField(default='bf9c0a', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format '+639XXXXXXXXX'", regex='^\\+63\\d{10}$')]),
        ),
    ]
