# Generated by Django 4.1.5 on 2023-03-21 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logs',
            new_name='ActivityHistory',
        ),
    ]
