# Generated by Django 4.2 on 2023-05-04 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_receiver', to='apps.department', verbose_name='Receiving Office:'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='tracking_no',
            field=models.CharField(default='e4b5ea', editable=False, max_length=255),
        ),
    ]
