# Generated by Django 4.1.5 on 2023-05-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_documents_tracking_no_alter_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='tracking_no',
            field=models.CharField(default='0a5d87', editable=False, max_length=255),
        ),
    ]
