# Generated by Django 4.1.5 on 2023-03-22 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_logs_activityhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityhistory',
            options={'verbose_name': 'Activity History', 'verbose_name_plural': 'Activity Histories'},
        ),
        migrations.RenameField(
            model_name='activityhistory',
            old_name='logs',
            new_name='history',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_faculty',
            new_name='is_employee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_school_official',
        ),
    ]
