# Generated by Django 4.2 on 2023-05-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_documents_tracking_no_alter_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='tracking_no',
            field=models.CharField(default='ee1d00', editable=False, max_length=255),
        ),
    ]
