# Generated by Django 4.2 on 2023-04-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='tracking_no',
            field=models.CharField(default='DOC-2b88c2', editable=False, max_length=255),
        ),
    ]
