# Generated by Django 4.2 on 2023-04-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_documents_tracking_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='receiver',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documents',
            name='tracking_no',
            field=models.CharField(default='DOC-f944fa', editable=False, max_length=255),
        ),
    ]
